############################################################
#
# 搜索微服务
# web访问端口号  约定：8007
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8007

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-search
  data:
    elasticsearch:
      cluster-name: imooc-elasticsearch
      cluster-nodes: 192.168.181.130:9300

