
server:
    port: ${port:8003}

spring:
    redis:
        port: 6379
        database: 0
        password: 123456
        host: 192.168.181.129

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置域名，在java代码中获取，这里是资源配置
website:
    domain-name: imoocnews.com