############################################################
#
# eureka 注册中心
# web访问端口号  约定：7000
#
############################################################
server:
  port: 7000
  tomcat:
    uri-encoding: UTF-8


############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springcloud-eureka

############################################################
#
# eureka配置信息
#
############################################################
eureka:
  instance:
    #eureka实例的hostname，可以是hostname，也可以自定义配置hostname
    hostname: localhost
  client:
    #是否要把当前的eureka server注册到自己
    register-with-eureka: true
    #从注册中心获得检索服务实例，server没有必要，直接false即可
    fetch-registry: false
    #单实例配置自己的服务地址，高可用集群则可配置多个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
